name: foodstore
version: '3'
services:
  mongodb:
    image: mongo
    
  backend:
    build: ~/app/backend
    container_name: backend
    ports:
      - "8000:8000"
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      # 映射您的实际路径
      - ~/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/app/frontend:/usr/share/nginx/html/frontend
      - ~/app/admin:/usr/share/nginx/html/admin