name: foodstore
version: '3'
services:
  mongodb:
    image: mongo
    
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET="520510you"
      - PRIVATE_KEY="MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2eAjai4e9nkK7v19yjyyxZ1gOECVtCJFhctLUTJRXRSyjtD+3VX5B+4N/9vWtqbYgQDZIW9ha9BdFROM2dE+TXy1zYGK+Keic/F9PRW6/DsXuC6HUkhC6pa4NjtBLz28Ohu9m3XO/ngM2YxP/glV6l5B/wD7XiJudWcOxgjcSYUqEXjZzexdvkirKXHaU7usoecrHbnbfRWTYxb0/hWHCmioE13pAgnLsK2ys3EVU1/jfFbFVWjxE23bKcOyfwCo98Zz2sbk4spuywTVrb7TK4Fl3bWfKXHBbnim74hR/SkEExsDHBXOqNUBvAEQzTO+Ow68YRcyNTMd+Kf5vIy2bAgMBAAECggEAU//qQ4GcWaRzoC63Z+uVbY3fsYmpUQpysuPDPsyKNaq4pBwkgOewmfuJS+2KqAnKuAoXczQk46oe1FqkJrtgrr1QFR84FccBONPNpJaYJwhMAgwE0fD0FpiTCdbG+T9jJtLjfv1PfdTmMbFm0WdUpn0DnmwIAfz3dnaOajdB1wl9tlrh6DZgs3qpeyiHQYXTFRLSj5DZ7RFZlsdRdEybsx14atrNsJwEnFR826fnrnKI6syHrWIcZFv/sGaW1sbn6D/O9abCP7TM3sTIpqLnwogeXKStmq0u4Kb+cf0ovABWctsZoKnmgEOzmBidhkvJQ/C4F7cc9smtJTgNaP63AQKBgQD6bh3WSxCR958G5lEIt7Irb6HqCLvNTxGoKEphqjvefSv283Br+ztMedaosEOzVGXUSmiDVCBDp2AedCXcHdbo5f/NlIuf1I0pva+AVDhqf+zE8US7OMx433VabYVcE++uP2rbQ8UhDdNG6WuhTtxxgoU/tqkhgq2ucLxN0jg8WwKBgQC6hvboeP1XpkAtmXWPJJbOZNcRAXb/lmKwWcnyN3CUMXI+D+YXoFgX5mIPdAt7sxNVh4MWvS0xu99nGRhhStxrdFsIri3WrRxLDC+Y7LERMRs/5xXnEkblQpRgYOoPwbUkHPbq/wVogFzZzj8bspYAOxl9cjdDfQOhtVMOzqyXwQKBgDGZZadvrpR6arC/JQWI/GzF61ei6y86ndCkSjcVtE3YlMCQbo+0boYzC2TVpFL8QD7PjeuU2d8MY2kkr+rsrgfqpcNdzFmXi23c98l+5L2TIJ3Q+z/pe/XkrCWA04ztFed4//z1azGkv1eoG30TVW3V3/ZCgzTz4NpP0bvICwNJAoGAArlHz7s8j9QYqdHM2qtBHIByd4ga8b6DcGnPPh87IJ7cOTXIOV4ZCzhNBEbAiCzkQmJ5MpLOnyRMLdg69+i88UDAt467kp/ygtIJu+Tw7PxXloZMVpR4vo5LVmDz6gj9GSrnHCVfMdh2AqQ1XbUs5ZH3XFKXpf+kVu8r6FJySMECgYEApFTQVn0srzt+yohmD6xx0tAclpqgcbJm8v60lj2ZJ1uCnkzeuDZJyxF2CdZhiOaskgbpNLsPZaMQ1XwEQn5Pn+YbLXCElbbhZN4C7ehXqkcbce5SBBqXtmjKw2kWG5X1trbY318BNT+k+DQBq0nLoQzGag7W4hL51nuAn9lt+JU="
      - PUBLIC_KEY="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2oOmhDFgpZP8t6gpsE4M7o8B7YoxaaMAxtkVlJQKi+6G0Moa0p3Ad/zPlv73sFzlhexItIvGBY39aOpXGWk8GZ1/en+Pyqptbrpori4oa4d2Km4w+iUPYqtABEJJGXHe0PCopBoc+DiwhEjPC7K6jsUYlaBsUnBC2jxAw9HShHqRPIEMfUF30sZwX7bja6Zlmp/kHmtEVQU8LHtnJOF40c6Qg2RitNIgHfyiSjaRGCHT4yn3ugs6h6vGHCMogaua9i1d5kVqleA0WB03657MwaL5DoPDBVMYzN8XvjKRTwn+fXrbP8qEnHhHgvN2WbRomlvcysZufb9eHzkx7MqJpwIDAQAB"
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      # 映射您的实际路径
      - ~/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/app/frontend/dist:/usr/share/nginx/html/frontend
      - ~/app/admin/dist:/usr/share/nginx/html/admin